### ISSUE TITLE
Have rest of the modules on the educational module page setup with placeholder data

### ISSUE THREAD

**Issue by zareentk** [DSC-McMaster-U/Gamified-Learning-Platform#115] opened 2024-02-12 00:29 UTC
Change the frontend code to include functionality for the modules after Module 1. A user should be able to open and click any module. The structure for the resto fo them should follow the first ones
<img width="157" alt="image" src="https://github.com/DSC-McMaster-U/Gamified-Learning-Platform/assets/80137085/3249fe17-cb4a-47ad-9b89-125765358156">

**Comment by alexchen2** [comment] 2024-02-12 00:30
This is a duplicate of/already handled within the ticket #110 (task of dynamically generating further module tabs and lesson panels using Jinja). 110 can be modified so that it takes in preset dummy data stored in the database, but we would definitely want to structure everything dynamically.

**Closed as completed** 2024-02-12 01:11 UTC
